name: Run test

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'
          
      - name: Display Java version
        run: java -version
        
      - name: Set up Gradle environment
        run: echo "JAVA_HOME=$JAVA_HOME"

      - name: Grant execute permissions for gradlew
        run: chmod +x ImageToText/gradlew

      - name: Run unit tests
        working-directory: ImageToText
        run: ./gradlew clean testDebug