name: Run test

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 18
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 18
          cache: 'gradle'
          
      - name: Display Java version and JAVA_HOME
        run: |
          java -version
          echo "JAVA_HOME=$JAVA_HOME"
        
      - name: Set Gradle Java home
        run: echo "org.gradle.java.home=$JAVA_HOME" >> ImageToText/gradle.properties

      - name: Grant execute permissions for gradlew
        run: chmod +x ImageToText/gradlew

      - name: Run unit tests
        working-directory: ImageToText
        run: ./gradlew clean testDebug -Dorg.gradle.java.home=$JAVA_HOME