on:
  push:
    branches: [main]

jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 18
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 18
          cache: 'gradle'
          
      - name: Display Java version and JAVA_HOME
        run: |
          java -version
          echo "JAVA_HOME=$JAVA_HOME"

      - name: Grant execute permissions for gradlew
        run: chmod +x ImageToText/gradlew

      - name: Build APK
        working-directory: ImageToText
        run: ./gradlew assembleDebug  # Adjust this command based on your build type

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: apk-artifact
          path: ImageToText/app/build/outputs/apk/debug/*.apk  # Adjust the path to your APK output

      - name: Send Email to Tester
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com  # Replace with your SMTP server address
          server_port: 465  # Change if needed
          username: ${{ secrets.SMTP_USERNAME }}  # Add your SMTP username to GitHub Secrets
          password: ${{ secrets.SMTP_PASSWORD }}  # Add your SMTP password to GitHub Secrets
          subject: "New APK Build Available"
          body: |
            A new build of the APK is available for testing.
            You can download it from the following link: 
            https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}#artifacts 
            ${{ steps.upload-artifact.outputs.artifact_url }}
          to: rakshithraj11@gmail.com  # Replace with the tester's email address
          from: rakshithraj11@gmail.com  # Replace with your email address
          secure: true 
