name: Deploy To Google Play

on:
  push:
    branches: [main]

jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 18
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 18
          cache: 'gradle'
          
      - name: Display Java version and JAVA_HOME
        run: |
          java -version
          echo "JAVA_HOME=$JAVA_HOME"

      - name: Grant execute permissions for gradlew
        run: chmod +x ImageToText/gradlew

      - name: Run unit tests
        working-directory: ImageToText
        run: ./gradlew clean testDebug

  distribute:
    name: Distribute bundle to Google Play
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 18
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 18
          cache: 'gradle'

      - name: Version Bump
        uses: chkfung/android-version-actions@v1.2.3
        with:
          working-directory: ImageToText
          gradlePath: app/build.gradle
          versionCode: ${{ github.run_number }}

      - name: Assemble Release Bundle
        working-directory: ImageToText
        run: ./gradlew bundleRelease

      - name: Sign Release
        uses: r0adkll/sign-android-release@v1
        with:
          working-directory: ImageToText
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.ANDROID_KEYSTORE }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          alias: ${{ secrets.ANDROID_DEVS_ALIAS }}
          keyPassword: ${{ secrets.ANDROID_DEVS_ALIAS_PASSWORD }}

      - name: Setup Authorization with Google Play Store
        working-directory: ImageToText
        run: echo '${{ secrets.PLAY_AUTH_JSON }}' > service_account.json

      - name: Deploy bundle to Google Play
        uses: r0adkll/upload-google-play@v1.1.3
        with:
          working-directory: ImageToText
          serviceAccountJson: service_account.json
          packageName: com.app.imagetotext
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          track: 'internal'
          status: 'completed'
          whatsNewDirectory: whatsNew/